@tool
extends EditorScript
class_name PVGamesEditableObjectPaletteBuilder

func _run() -> void:
	print("B8A palette scenes are generated by src/tools/editor/pvgames_editable_object_palette_builder.py.")
	print("Run that Python builder to refresh scenes, normalized index, contact sheets, and reports.")
