#!/usr/bin/env python3
"""Generate Corner Store Cashout production mission scene."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
SCENE_PATH = ROOT / "scenes/missions_iso/CornerStoreCashout_Editable.tscn"
MISSION_ID = "corner_store_cashout"
REQUIREMENT_SCRIPT = "res://src/missions/iso/authoring/core/MissionRequirement.gd"
REQUIREMENT_SET_SCRIPT = "res://src/missions/iso/authoring/core/RequirementSet.gd"
BLOCKOUT_TILESET = "res://assets/tilesets/iso_blockout_clean/IsoBlockoutTileset_Clean.tres"
MARKER_TILESET = "res://assets/tilesets/marker_authoring/MarkerAuthoringTileset.tres"
PV_FLOOR_TILESET = "res://assets/tilesets/pvgames_paintable/PVGamesFloorPaintVisualTileset.tres"
PV_WALL_TILESET = "res://assets/tilesets/pvgames_paintable/PVGamesWallPaintVisualTileset.tres"

SCRIPTS = {
    "iso_base": "res://src/levels/IsoMissionBase.gd",
    "definition": "res://assets/missions/corner_store_cashout_definition.tres",
    "bootstrap": "res://src/missions/iso/dev/CornerStoreCashoutLayoutBootstrap.gd",
    "bridge": "res://src/missions/iso/runtime/authoring/MissionInteractionBridge.gd",
    "alert": "res://src/missions/iso/runtime/MissionAlertController.gd",
    "mission_ctrl": "res://src/missions/iso/runtime/CornerStoreCashoutMissionController.gd",
    "encounter_ctrl": "res://src/missions/iso/runtime/CornerStoreCashoutEncounterController.gd",
    "search": "res://src/missions/iso/authoring/mechanics/SearchZone.gd",
    "reward": "res://src/missions/iso/authoring/mechanics/RewardNode.gd",
    "pickup": "res://src/missions/iso/authoring/mechanics/InventoryPickupNode.gd",
    "locked": "res://src/missions/iso/authoring/mechanics/LockedInteractionNode.gd",
    "container": "res://src/missions/iso/authoring/mechanics/InteractiveContainer.gd",
    "route": "res://src/missions/iso/authoring/mechanics/RouteUnlockNode.gd",
    "terminal": "res://src/missions/iso/authoring/mechanics/TerminalHackNode.gd",
    "power": "res://src/missions/iso/authoring/mechanics/PowerCircuitNode.gd",
    "plate": "res://src/missions/iso/authoring/mechanics/PressurePlateNode.gd",
    "timed": "res://src/missions/iso/authoring/mechanics/TimedSwitchNode.gd",
    "companion": "res://src/missions/iso/authoring/mechanics/CompanionCommandPoint.gd",
    "bentley_wait": "res://src/missions/iso/authoring/mechanics/BentleyWaitMarker.gd",
    "bentley_crawl": "res://src/missions/iso/authoring/mechanics/BentleyCrawlspaceConnector.gd",
    "noise": "res://src/missions/iso/runtime/noise/NoiseEmitterNode.gd",
    "distraction": "res://src/missions/iso/authoring/mechanics/DistractionObject.gd",
    "eavesdrop": "res://src/missions/iso/authoring/mechanics/EavesdropZone.gd",
    "dead_drop": "res://src/missions/iso/authoring/mechanics/DeadDropNode.gd",
    "side_obj": "res://src/missions/iso/authoring/mechanics/SideObjectiveNode.gd",
    "route_action": "res://src/missions/iso/authoring/mechanics/EncounterRouteActionNode.gd",
    "extraction": "res://src/missions/iso/authoring/mechanics/ExtractionZone.gd",
    "investigation": "res://src/missions/iso/authoring/mechanics/InvestigationPointNode.gd",
    "routine": "res://src/missions/iso/authoring/mechanics/RoutineOverrideNode.gd",
    "audit": "res://src/missions/iso/authoring/mechanics/AuditTrailCleanupNode.gd",
    "heat_sink": "res://src/missions/iso/authoring/mechanics/HeatSinkObject.gd",
    "believable": "res://src/missions/iso/authoring/mechanics/BelievableTaskZone.gd",
    "protocol": "res://src/missions/iso/authoring/mechanics/ProtocolZone.gd",
    "object_swap": "res://src/missions/iso/authoring/mechanics/ObjectSwapNode.gd",
    "bug_plant": "res://src/missions/iso/authoring/mechanics/BugPlantNode.gd",
    "scheme": "res://src/missions/iso/authoring/mechanics/SchemeCardTriggerNode.gd",
	"sequence": "res://src/missions/iso/authoring/sequences/CustomSequenceRunner.gd",
    "proof_harness": "res://src/missions/iso/dev/CornerStoreCashoutIntegratedProofHarness.gd",
}


def rect_shape(size: str = "96, 96") -> str:
    return f"""[sub_resource type="RectangleShape2D" id="RectangleShape2D_{size.replace(', ', '_')}"]
size = Vector2({size})
"""


def area_node(name: str, script_key: str, pos: tuple[float, float], props: dict[str, str], shape_id: str) -> list[str]:
    lines = [f'[node name="{name}" type="Area2D" parent="GameplayRoot/MissionMechanics"]']
    if pos != (0, 0):
        lines.append(f"position = Vector2({pos[0]}, {pos[1]})")
    lines.append(f'script = ExtResource("{script_key}")')
    for key, value in props.items():
        lines.append(f"{key} = {value}")
    lines.append("")
    lines.append(f'[node name="CollisionShape2D" type="CollisionShape2D" parent="GameplayRoot/MissionMechanics/{name}"]')
    lines.append(f"shape = SubResource(\"{shape_id}\")")
    lines.append("")
    return lines


def main() -> None:
    shape_id = "RectangleShape2D_96_96"
    ext_resources = [
        f'[ext_resource type="Script" path="{SCRIPTS["iso_base"]}" id="1"]',
        f'[ext_resource type="Resource" path="{SCRIPTS["definition"]}" id="2"]',
        f'[ext_resource type="Script" path="{SCRIPTS["bootstrap"]}" id="3"]',
        f'[ext_resource type="Script" path="{REQUIREMENT_SCRIPT}" id="req_script"]',
        f'[ext_resource type="Script" path="{REQUIREMENT_SET_SCRIPT}" id="reqset_script"]',
        f'[ext_resource type="TileSet" path="{BLOCKOUT_TILESET}" id="blockout_tileset"]',
        f'[ext_resource type="TileSet" path="{MARKER_TILESET}" id="marker_tileset"]',
        f'[ext_resource type="TileSet" path="{PV_FLOOR_TILESET}" id="pv_floor_tileset"]',
        f'[ext_resource type="TileSet" path="{PV_WALL_TILESET}" id="pv_wall_tileset"]',
    ]
    id_map = {k: str(i + 4) for i, k in enumerate(
        [k for k in SCRIPTS if k not in ("iso_base", "definition", "bootstrap")]
    )}
    for key, path in SCRIPTS.items():
        if key in ("iso_base", "definition", "bootstrap"):
            continue
        ext_resources.append(f'[ext_resource type="Script" path="{path}" id="{id_map[key]}"]')

    lines: list[str] = [
        f"[gd_scene load_steps={len(SCRIPTS) + 8} format=3]",
        "",
        *ext_resources,
        "",
        rect_shape("96, 96"),
        "",
        '[sub_resource type="Resource" id="Requirement_csc_badge"]',
        'script = ExtResource("req_script")',
        'requirement_id = &"csc_requires_badge"',
        'fact_type = &"mission_flag"',
        'key = "csc_badge_collected"',
        'operator = 2',
        'expected_value_type = "exists"',
        'fail_message = "Need an employee credential first."',
        "",
        '[sub_resource type="Resource" id="RequirementSet_csc_office_door"]',
        'script = ExtResource("reqset_script")',
        'requirements = Array[ExtResource("req_script")]([SubResource("Requirement_csc_badge")])',
        'locked_message = "Need an employee credential first."',
        "",
        '[node name="CornerStoreCashout_Editable" type="Node2D"]',
        'script = ExtResource("1")',
        "mission_definition = ExtResource(\"2\")",
        "auto_generate_from_definition = false",
        "",
        '[node name="CornerStoreCashoutLayoutBootstrap" type="Node" parent="."]',
        'script = ExtResource("3")',
        "",
        '[node name="GameplayRoot" type="Node2D" parent="."]',
        "",
        '[node name="LayoutRoot" type="Node2D" parent="GameplayRoot"]',
        "",
        '[node name="FloorLayer" type="TileMapLayer" parent="GameplayRoot/LayoutRoot"]',
        'tile_set = ExtResource("blockout_tileset")',
        "y_sort_enabled = true",
        "",
        '[node name="WallLayer" type="TileMapLayer" parent="GameplayRoot/LayoutRoot"]',
        'tile_set = ExtResource("blockout_tileset")',
        "y_sort_enabled = true",
        "",
        '[node name="CoverLayer" type="TileMapLayer" parent="GameplayRoot/LayoutRoot"]',
        'tile_set = ExtResource("blockout_tileset")',
        "y_sort_enabled = true",
        "",
        '[node name="CollisionBarrierLayer" type="TileMapLayer" parent="GameplayRoot/LayoutRoot"]',
        'tile_set = ExtResource("blockout_tileset")',
        "y_sort_enabled = true",
        "",
        '[node name="MarkerTileLayer" type="TileMapLayer" parent="GameplayRoot/LayoutRoot"]',
        'tile_set = ExtResource("marker_tileset")',
        "y_sort_enabled = true",
        "",
        '[node name="GameplayFloorLayer" type="TileMapLayer" parent="GameplayRoot"]',
        "y_sort_enabled = true",
        "",
        '[node name="GameplayCollisionLayer" type="TileMapLayer" parent="GameplayRoot"]',
        "y_sort_enabled = true",
        "",
        '[node name="GameplayMarkersLayer" type="TileMapLayer" parent="GameplayRoot"]',
        "y_sort_enabled = true",
        "",
        '[node name="EntityRoot" type="Node2D" parent="GameplayRoot"]',
        "y_sort_enabled = true",
        "",
        '[node name="Enemies" type="Node2D" parent="GameplayRoot/EntityRoot"]',
        "",
        '[node name="Interactables" type="Node2D" parent="GameplayRoot/EntityRoot"]',
        "",
        '[node name="SpawnPoints" type="Node2D" parent="GameplayRoot"]',
        "",
        '[node name="default" type="Marker2D" parent="GameplayRoot/SpawnPoints"]',
        "position = Vector2(-480, 40)",
        "",
        '[node name="RuntimeHelpers" type="Node" parent="GameplayRoot"]',
        "",
        '[node name="CornerStoreCashoutMissionController" type="Node" parent="GameplayRoot/RuntimeHelpers"]',
        f'script = ExtResource("{id_map["mission_ctrl"]}")',
        f'mission_id = "{MISSION_ID}"',
        "",
        '[node name="MissionInteractionBridge" type="Node" parent="GameplayRoot/RuntimeHelpers"]',
        f'script = ExtResource("{id_map["bridge"]}")',
        "include_legacy_candidates = false",
        'player_path = NodePath("../../EntityRoot/Player")',
        "",
        '[node name="MissionAlertController" type="Node" parent="GameplayRoot/RuntimeHelpers"]',
        f'script = ExtResource("{id_map["alert"]}")',
        f'mission_id = "{MISSION_ID}"',
        "",
        '[node name="CornerStoreCashoutEncounterController" type="Node" parent="GameplayRoot/RuntimeHelpers"]',
        f'script = ExtResource("{id_map["encounter_ctrl"]}")',
        f'mission_id_override = "{MISSION_ID}"',
        "start_on_ready = false",
        'encounter_id = &"corner_store_cashout_cleanup"',
        'display_name = "Corner Store Cleanup"',
        "",
        '[node name="MissionMechanics" type="Node2D" parent="GameplayRoot"]',
        "",
    ]

    mid = MISSION_ID
    common = {
        "mission_id_override": f'"{mid}"',
    }

    mechanics = [
        ("SearchZone_csc_entry_clue", "search", (-300, -20), {
            **common,
            "mechanic_id": "&\"csc_entry_clue\"",
            "display_name": "\"Scheduling Clipboard\"",
            "search_kind": "\"counter\"",
            "searched_flag": "&\"csc_entry_clue_found\"",
            "prompt_text": "\"Press E: Check scheduling clipboard\"",
            "found_message": "\"Back-office keypad code is taped under the clipboard.\"",
        }),
        ("SearchZone_csc_back_hint", "search", (60, -150), {
            **common,
            "mechanic_id": "&\"csc_back_hint\"",
            "display_name": "\"Employee Calendar\"",
            "search_kind": "\"desk\"",
            "searched_flag": "&\"csc_back_room_hint_found\"",
            "prompt_text": "\"Press E: Read employee calendar\"",
        }),
        ("InventoryPickupNode_csc_fake_badge", "pickup", (-80, -30), {
            **common,
            "mechanic_id": "&\"csc_fake_badge\"",
            "display_name": "\"Borrowed Name Tag\"",
            "item_id": "&\"corner_store_vendor_badge\"",
            "reward_id": "&\"corner_store_vendor_badge\"",
            "collected_flag": "&\"csc_badge_collected\"",
            "prompt_text": "\"Press E: Pocket the spare name tag\"",
        }),
        ("LockedInteractionNode_csc_office_door", "locked", (220, -130), {
            **common,
            "mechanic_id": "&\"csc_office_door\"",
            "display_name": "\"Employee-Only Door\"",
            "lock_kind": "\"door\"",
            "unlocked_flag": "&\"csc_checkpoint_open\"",
            "prompt_text": "\"Press E: Swipe employee badge\"",
            "locked_prompt_text": "\"Need an employee credential first.\"",
            "requirements": 'SubResource("RequirementSet_csc_office_door")',
        }),
        ("InteractiveContainer_csc_cash_drawer", "container", (340, -160), {
            **common,
            "mechanic_id": "&\"csc_cash_drawer\"",
            "display_name": "\"Cash Drawer\"",
            "prompt_text": "\"Press E: Pop the cash drawer\"",
        }),
        ("RewardNode_csc_cash_envelope", "reward", (400, -190), {
            **common,
            "mechanic_id": "&\"csc_cash_envelope\"",
            "display_name": "\"Misplaced Cash Envelope\"",
            "reward_kind": "\"evidence\"",
            "reward_id": "&\"corner_store_cash_envelope\"",
            "collected_flag": "&\"csc_cash_envelope_collected\"",
            "prompt_text": "\"Press E: Grab the cash envelope\"",
        }),
        ("RewardNode_csc_scam_folder", "reward", (440, -130), {
            **common,
            "mechanic_id": "&\"csc_scam_folder\"",
            "display_name": "\"Insurance Scam Folder\"",
            "reward_kind": "\"evidence\"",
            "reward_id": "&\"corner_store_insurance_scam_folder\"",
            "collected_flag": "&\"csc_evidence_collected\"",
            "prompt_text": "\"Press E: Take the scam evidence folder\"",
        }),
        ("TerminalHackNode_csc_security_log", "terminal", (500, -50), {
            **common,
            "mechanic_id": "&\"csc_security_log\"",
            "display_name": "\"Security Log Terminal\"",
            "hack_id": "&\"csc_security_log_hack\"",
            "completed_flag": "&\"csc_terminal_hacked\"",
            "prompt_text": "\"Press E: Hack security log\"",
        }),
        ("PowerCircuitNode_csc_camera_power", "power", (520, 90), {
            **common,
            "mechanic_id": "&\"csc_camera_power\"",
            "display_name": "\"Camera Power Circuit\"",
            "circuit_id": "&\"csc_camera_loop\"",
            "prompt_text": "\"Press E: Rewire camera loop\"",
        }),
        ("PressurePlateNode_csc_stockroom_plate", "plate", (460, 110), {
            **common,
            "mechanic_id": "&\"csc_stockroom_plate\"",
            "display_name": "\"Stockroom Pressure Plate\"",
            "plate_id": "&\"csc_stockroom_plate\"",
            "prompt_text": "\"Stand on stockroom plate\"",
        }),
        ("TimedSwitchNode_csc_freezer_timer", "timed", (480, 130), {
            **common,
            "mechanic_id": "&\"csc_freezer_timer\"",
            "display_name": "\"Freezer Timer Switch\"",
            "switch_id": "&\"csc_freezer_timer\"",
            "prompt_text": "\"Press E: Trip freezer timer\"",
        }),
        ("RouteUnlockNode_csc_alley_route", "route", (540, 30), {
            **common,
            "mechanic_id": "&\"csc_alley_route\"",
            "display_name": "\"Alley Exit Route\"",
            "route_id": "&\"csc_alley_extract\"",
            "route_flag": "&\"csc_alley_route_unlocked\"",
            "prompt_text": "\"Press E: Unlock alley exit\"",
        }),
        ("CompanionCommandPoint_csc_bentley_bark", "companion", (120, 100), {
            **common,
            "mechanic_id": "&\"csc_bentley_bark\"",
            "display_name": "\"Bentley Bark Point\"",
            "command_type": "\"bark\"",
            "command_label": "\"Bentley barks at the guard\"",
            "prompt_text": "\"Press E: Tell Bentley to bark\"",
        }),
        ("BentleyWaitMarker_csc_bentley_wait", "bentley_wait", (80, 140), {
            **common,
            "mechanic_id": "&\"csc_bentley_wait\"",
            "display_name": "\"Bentley Wait\"",
            "prompt_text": "\"Press E: Bentley wait here\"",
        }),
        ("BentleyCrawlspaceConnector_csc_stock_crawl", "bentley_crawl", (200, 150), {
            **common,
            "mechanic_id": "&\"csc_stock_crawl\"",
            "display_name": "\"Stockroom Crawlspace\"",
            "prompt_text": "\"Press E: Send Bentley through crawlspace\"",
        }),
        ("NoiseEmitterNode_csc_chip_aisle_noise", "noise", (220, 60), {
            **common,
            "mechanic_id": "&\"csc_chip_aisle_noise\"",
            "display_name": "\"Chip Aisle Noise\"",
            "noise_id": "&\"csc_chip_aisle_noise\"",
            "noise_kind": "\"decoy\"",
            "noise_strength": "0.55",
            "prompt_text": "\"Press E: Knock over chip display\"",
        }),
        ("DistractionObject_csc_spilled_drink", "distraction", (260, 80), {
            **common,
            "mechanic_id": "&\"csc_spilled_drink\"",
            "display_name": "\"Spilled Slushie\"",
            "distraction_id": "&\"csc_spilled_drink\"",
            "prompt_text": "\"Press E: Spill distraction slushie\"",
        }),
        ("EavesdropZone_csc_side_job_listen", "eavesdrop", (-140, 120), {
            **common,
            "mechanic_id": "&\"csc_side_job_listen\"",
            "display_name": "\"Stockroom Vent Listen\"",
            "eavesdrop_id": "&\"csc_side_job_listen\"",
            "prompt_text": "\"Press E: Eavesdrop on scam call\"",
        }),
        ("DeadDropNode_csc_alley_drop", "dead_drop", (320, 200), {
            **common,
            "mechanic_id": "&\"csc_alley_drop\"",
            "display_name": "\"Alley Dead Drop\"",
            "drop_id": "&\"csc_alley_drop\"",
            "prompt_text": "\"Press E: Plant dead drop\"",
        }),
        ("SideObjectiveNode_csc_coupon_scam", "side_obj", (300, 220), {
            **common,
            "mechanic_id": "&\"csc_coupon_scam\"",
            "display_name": "\"Bonus Coupon Scam\"",
            "side_objective_id": "&\"csc_coupon_scam\"",
            "prompt_text": "\"Press E: Photograph coupon scam board\"",
        }),
        ("EncounterRouteActionNode_csc_clean_social", "route_action", (260, 40), {
            **common,
            "mechanic_id": "&\"csc_route_clean_social\"",
            "display_name": "\"Clean Social Route\"",
            "route_method": "\"run_clean_social_route\"",
            "route_id": "&\"clean_social_route\"",
            "route_label": "\"Clean Social Helper\"",
            "route_choice_flag": "&\"csc_route_selected\"",
            "route_specific_flag": "&\"csc_route_clean_social\"",
            "controller_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutEncounterController")',
            "required_controller_bool_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutMissionController")',
            "required_controller_bool_property": "&\"back_office_unlocked\"",
            "progress_locked_message": "\"Recover back-office evidence before choosing a cleanup route.\"",
            "prompt_text": "\"Press E: Act like a delivery helper\"",
        }),
        ("EncounterRouteActionNode_csc_bentley_route", "route_action", (260, 80), {
            **common,
            "mechanic_id": "&\"csc_route_bentley\"",
            "display_name": "\"Bentley Distraction Route\"",
            "route_method": "\"run_bentley_distraction_route\"",
            "route_id": "&\"bentley_distraction_route\"",
            "route_label": "\"Bentley Distraction\"",
            "route_choice_flag": "&\"csc_route_selected\"",
            "route_specific_flag": "&\"csc_route_bentley\"",
            "controller_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutEncounterController")',
            "required_controller_bool_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutMissionController")',
            "required_controller_bool_property": "&\"back_office_unlocked\"",
            "prompt_text": "\"Press E: Let Bentley cause a scene\"",
        }),
        ("EncounterRouteActionNode_csc_evidence_route", "route_action", (260, 120), {
            **common,
            "mechanic_id": "&\"csc_route_evidence\"",
            "display_name": "\"Evidence Route\"",
            "route_method": "\"run_evidence_route\"",
            "route_id": "&\"evidence_route\"",
            "route_label": "\"Evidence / Paper Trail\"",
            "route_choice_flag": "&\"csc_route_selected\"",
            "route_specific_flag": "&\"csc_route_evidence\"",
            "controller_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutEncounterController")',
            "required_controller_bool_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutMissionController")',
            "required_controller_bool_property": "&\"back_office_unlocked\"",
            "prompt_text": "\"Press E: Scrub the security log\"",
        }),
        ("EncounterRouteActionNode_csc_messy_route", "route_action", (260, 160), {
            **common,
            "mechanic_id": "&\"csc_route_messy\"",
            "display_name": "\"Messy Authority Route\"",
            "route_method": "\"run_messy_authority_route\"",
            "route_id": "&\"messy_authority_route\"",
            "route_label": "\"Messy Authority Bluff\"",
            "route_choice_flag": "&\"csc_route_selected\"",
            "route_specific_flag": "&\"csc_route_messy\"",
            "controller_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutEncounterController")',
            "required_controller_bool_path": 'NodePath("../../RuntimeHelpers/CornerStoreCashoutMissionController")',
            "required_controller_bool_property": "&\"back_office_unlocked\"",
            "prompt_text": "\"Press E: Bluff the guard with fake authority\"",
        }),
        ("ExtractionZone_csc_alley_extract", "extraction", (640, 40), {
            **common,
            "mechanic_id": "&\"csc_alley_extract\"",
            "display_name": "\"Alley Extraction\"",
            "extraction_tag": "&\"csc_alley_extract\"",
            "extraction_flag": "&\"csc_extracted\"",
            "complete_mission_on_success": "true",
            "required_objective_ids": "Array[StringName]([&\"recover_cashout_evidence\", &\"choose_cleanup_route\"])",
            "prompt_text": "\"Press E: Slip out the alley\"",
            "missing_objective_message": "\"Finish evidence and choose a cleanup route first.\"",
        }),
        ("InvestigationPointNode_csc_guard_investigation", "investigation", (160, -80), {
            **common,
            "mechanic_id": "&\"csc_guard_investigation\"",
            "display_name": "\"Guard Investigation Point\"",
            "investigation_id": "&\"csc_guard_investigation\"",
            "prompt_text": "\"Press E: Inspect guard routine\"",
        }),
        ("RoutineOverrideNode_csc_clerk_routine", "routine", (140, -100), {
            **common,
            "mechanic_id": "&\"csc_clerk_routine\"",
            "display_name": "\"Clerk Routine Override\"",
            "routine_id": "&\"csc_clerk_routine\"",
            "prompt_text": "\"Press E: Nudge clerk routine\"",
        }),
        ("AuditTrailCleanupNode_csc_log_cleanup", "audit", (400, -40), {
            **common,
            "mechanic_id": "&\"csc_log_cleanup\"",
            "display_name": "\"Audit Trail Cleanup\"",
            "cleanup_id": "&\"csc_log_cleanup\"",
            "prompt_text": "\"Press E: Weaken audit trail\"",
        }),
        ("HeatSinkObject_csc_slushie_sink", "heat_sink", (360, -60), {
            **common,
            "mechanic_id": "&\"csc_slushie_sink\"",
            "display_name": "\"Slushie Heat Sink\"",
            "heat_sink_id": "&\"csc_slushie_sink\"",
            "prompt_text": "\"Press E: Blame the slushie machine\"",
        }),
        ("BelievableTaskZone_csc_restock_task", "believable", (-220, -60), {
            **common,
            "mechanic_id": "&\"csc_restock_task\"",
            "display_name": "\"Believable Restock Task\"",
            "task_id": "&\"restock_neon_aisle\"",
            "prompt_text": "\"Press E: Pretend to restock neon aisle\"",
        }),
        ("ProtocolZone_csc_clerk_protocol", "protocol", (-240, -80), {
            **common,
            "mechanic_id": "&\"csc_clerk_protocol\"",
            "display_name": "\"Clerk Protocol Zone\"",
            "protocol_id": "&\"clerk_small_talk\"",
            "prompt_text": "\"Press E: Run clerk small-talk protocol\"",
        }),
        ("ObjectSwapNode_csc_price_tag_swap", "object_swap", (280, 180), {
            **common,
            "mechanic_id": "&\"csc_price_tag_swap\"",
            "display_name": "\"Price Tag Swap\"",
            "swap_id": "&\"csc_price_tag_swap\"",
            "prompt_text": "\"Press E: Swap price tags\"",
        }),
        ("BugPlantNode_csc_stock_bug", "bug_plant", (350, 160), {
            **common,
            "mechanic_id": "&\"csc_stock_bug\"",
            "display_name": "\"Stockroom Bug Plant\"",
            "bug_id": "&\"csc_stock_bug\"",
            "prompt_text": "\"Press E: Plant listening bug\"",
        }),
        ("SchemeCardTriggerNode_csc_card_hook", "scheme", (-420, 0), {
            **common,
            "mechanic_id": "&\"csc_card_hook\"",
            "display_name": "\"Scheme Card Hook\"",
            "modifier_set_id": "&\"vendor_restock_helper\"",
            "prompt_text": "\"Scheme card setup hook\"",
            "apply_on_ready": "false",
        }),
    ]

    for name, script_key, pos, props in mechanics:
        lines.extend(area_node(name, id_map[script_key], pos, props, shape_id))

    lines.extend([
        '[node name="CustomSequenceRunner_csc_side_job" type="Node" parent="GameplayRoot/MissionMechanics"]',
        f'script = ExtResource("{id_map["sequence"]}")',
        f'mission_id_override = "{mid}"',
        'sequence_id = &"csc_side_job_sequence"',
        "",
        '[node name="ArtRoot" type="Node2D" parent="."]',
        "y_sort_enabled = true",
        "",
        '[node name="GroundArtLayer" type="TileMapLayer" parent="ArtRoot"]',
        'tile_set = ExtResource("pv_floor_tileset")',
        "collision_enabled = false",
        "y_sort_enabled = true",
        "",
        '[node name="WallArtLayer" type="TileMapLayer" parent="ArtRoot"]',
        'tile_set = ExtResource("pv_wall_tileset")',
        "collision_enabled = false",
        "y_sort_enabled = true",
        "",
        '[node name="PropArtLayer" type="TileMapLayer" parent="ArtRoot"]',
        "collision_enabled = false",
        "y_sort_enabled = true",
        "",
        '[node name="DecorBelowLayer" type="TileMapLayer" parent="ArtRoot"]',
        "collision_enabled = false",
        "",
        '[node name="DecorAboveLayer" type="TileMapLayer" parent="ArtRoot"]',
        "collision_enabled = false",
        "",
        '[node name="LightingLayer" type="TileMapLayer" parent="ArtRoot"]',
        "collision_enabled = false",
        "",
        '[node name="DebugProof" type="CanvasLayer" parent="GameplayRoot"]',
        "",
        '[node name="ProofPanel" type="PanelContainer" parent="GameplayRoot/DebugProof"]',
        "visible = false",
        "offset_left = 12.0",
        "offset_top = 12.0",
        "offset_right = 420.0",
        "offset_bottom = 120.0",
        "",
        '[node name="VBox" type="VBoxContainer" parent="GameplayRoot/DebugProof/ProofPanel"]',
        "",
        '[node name="StatusLabel" type="Label" parent="GameplayRoot/DebugProof/ProofPanel/VBox"]',
        'text = "Corner Store proof harness (debug only)"',
        "autowrap_mode = 3",
        "",
        '[node name="Run Integrated Proof" type="Button" parent="GameplayRoot/DebugProof/ProofPanel/VBox"]',
        'text = "Run Integrated Proof"',
        "",
        '[node name="ProofHarness" type="Control" parent="GameplayRoot/DebugProof/ProofPanel/VBox"]',
        f'script = ExtResource("{id_map["proof_harness"]}")',
        "layout_mode = 2",
        'mission_controller_path = NodePath("../../../../RuntimeHelpers/CornerStoreCashoutMissionController")',
        'encounter_controller_path = NodePath("../../../../RuntimeHelpers/CornerStoreCashoutEncounterController")',
        'status_label_path = NodePath("../StatusLabel")',
        "",
        '[node name="CameraBounds" type="Node2D" parent="GameplayRoot"]',
        "",
        '[node name="Camera2D" type="Camera2D" parent="."]',
        "position = Vector2(80, 0)",
        "limit_left = -900",
        "limit_top = -500",
        "limit_right = 900",
        "limit_bottom = 500",
        "",
    ])

    SCENE_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCENE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {SCENE_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
